### ISSUE TITLE
Please let me unsubscribe

### ISSUE THREAD

**Issue by attilaolah** [goffee/goffee#1]
…from the email notifications.

Also, they are often false. I host my site on GitHub pages, and I doubt that it is down as often as Goffee says so.

**Comment by kytrinyx** [comment]
+10

I removed all the checks, and am still getting emails.

**Comment by sdsykes** [comment]
@kytrinyx that is strange, we are looking into it asap.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by sdsykes** [comment]
This is resolved. Goffee was always somewhat dependent on the exit nodes of Tor actually working, which they sometimes don't in various ways. We've disabled email notifications for now (unless we come back and revive the project at some point.) But anyway if we do we'll make sure the database is cleaned of any old subscriptions.

**Comment by kytrinyx** [comment]
Thanks, @sdsykes!
