### ISSUE TITLE
domain broken?

### ISSUE THREAD

**Issue by jbenet** [goffee/goffee#7]
goffee.io seems down.

**Comment by eduncan911** [comment]
```
Domain Status:  pendingDelete / Final Phase
Expiry :    2016-01-24

Unless it is renewed it will be deleted in a batch run started at 2016-04-24 00:30 (UTC)
```

:-1:

**Comment by sdsykes** [comment]
Yes, in the end we didn't develop the project further as we found that tor exit nodes are not reliable enough in the long run. The domain has lapsed.
